import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="max-h-screen">
          <Navbar />
          <div className="grid grid-cols-12 gap-5">
            <div className="col-span-1">
              <Sidebar />
            </div>
            <div className=" col-span-12 lg:col-span-11">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
